### ISSUE TITLE
Offset test fails on Linux x86

### ISSUE THREAD

**Issue by johnor** [evilcorpltd/stdlib2#16]
The offset there is 4 bytes, not 8. Should we have a define? Or different files for x86 and x64?

**Comment by robinlinden** [comment]
I wasn't really planning on supporting x86 before you opened a PR for it, but I thought doubles would always be aligned to 8 byte. Turns out that's not the case! In structs on x86, they have a 4 byte alignment requirement. 😁 

Maybe we should replace the double with a float so we can (probably? didn't look it up) use 4 as the offsetof for all platforms?

See discussion: https://stackoverflow.com/questions/44877185/alignment-of-a-struct-with-two-doubles-is-4-even-though-double-is-aligned-to-8
